const tests = [
  { id: 1, question: "She ____ to school every day.", options: ["go", "goes", "going", "gone"], answer: "goes" },
  { id: 2, question: "I ____ a book yesterday.", options: ["read", "reads", "reading", "readed"], answer: "read" },
  { id: 3, question: "They ____ watching TV now.", options: ["is", "are", "was", "be"], answer: "are" },
  { id: 4, question: "He ____ in London last year.", options: ["live", "lived", "lives", "living"], answer: "lived" },
  { id: 5, question: "We ____ to the cinema tomorrow.", options: ["go", "goes", "are going", "going"], answer: "are going" },
  { id: 6, question: "The plural of 'child' is ____.", options: ["childs", "childes", "children", "childrens"], answer: "children" },
  { id: 7, question: "There ____ some milk in the fridge.", options: ["is", "are", "was", "were"], answer: "is" },
  { id: 8, question: "Choose the correct article: She is ____ engineer.", options: ["a", "an", "the", "no article"], answer: "an" },
  { id: 9, question: "I have lived here ____ 2010.", options: ["for", "since", "at", "from"], answer: "since" },
  { id: 10, question: "He is taller ____ his brother.", options: ["as", "then", "than", "to"], answer: "than" },
  { id: 11, question: "If I ____ you, I would study more.", options: ["am", "was", "were", "be"], answer: "were" },
  { id: 12, question: "We ____ lunch when she arrived.", options: ["had", "were having", "have", "having"], answer: "were having" },
  { id: 13, question: "Can you speak English? – Yes, I ____.", options: ["can", "do", "am", "have"], answer: "can" },
  { id: 14, question: "She sings ____ than her sister.", options: ["good", "better", "well", "best"], answer: "better" },
  { id: 15, question: "I’m looking forward to ____ you soon.", options: ["see", "seeing", "to see", "seen"], answer: "seeing" },
  { id: 16, question: "We haven’t seen him ____ Monday.", options: ["since", "for", "from", "by"], answer: "since" },
  { id: 17, question: "He is interested ____ art.", options: ["on", "in", "at", "to"], answer: "in" },
  { id: 18, question: "Let’s go out, ____?", options: ["will we", "do we", "shall we", "won’t we"], answer: "shall we" },
  { id: 19, question: "The opposite of 'happy' is ____.", options: ["sad", "angry", "bad", "cry"], answer: "sad" },
  { id: 20, question: "My car is ____ than yours.", options: ["fast", "faster", "fastest", "more fast"], answer: "faster" },
  { id: 21, question: "She has ____ friends in London.", options: ["much", "a few", "little", "many"], answer: "many" },
  { id: 22, question: "I prefer coffee ____ tea.", options: ["to", "than", "for", "from"], answer: "to" },
  { id: 23, question: "I have never ____ to Japan.", options: ["go", "been", "went", "gone"], answer: "been" },
  { id: 24, question: "He plays football very ____.", options: ["good", "well", "better", "best"], answer: "well" },
  { id: 25, question: "Where ____ you yesterday?", options: ["are", "were", "was", "be"], answer: "were" },
  { id: 26, question: "The synonym of 'big' is ____.", options: ["small", "tiny", "large", "short"], answer: "large" },
  { id: 27, question: "How ____ sugar do you want?", options: ["many", "much", "few", "little"], answer: "much" },
  { id: 28, question: "He is a very ____ person.", options: ["intelligent", "intelligence", "intelligently", "intellect"], answer: "intelligent" },
  { id: 29, question: "The sun ____ in the east.", options: ["rise", "rises", "rose", "rising"], answer: "rises" },
  { id: 30, question: "We have to finish it ____ Friday.", options: ["on", "in", "at", "by"], answer: "by" },
  { id: 31, question: "I’m tired ____ working all day.", options: ["for", "of", "about", "from"], answer: "of" },
  { id: 32, question: "They haven’t arrived yet, ____?", options: ["aren’t they", "have they", "haven’t they", "did they"], answer: "have they" },
  { id: 33, question: "The book was written ____ Shakespeare.", options: ["by", "from", "of", "with"], answer: "by" },
  { id: 34, question: "He drives ____ than I expected.", options: ["carefully", "more carefully", "careful", "most carefully"], answer: "more carefully" },
  { id: 35, question: "You ____ smoke here.", options: ["mustn’t", "don’t have to", "should", "can"], answer: "mustn’t" },
  { id: 36, question: "He didn’t go to work because he ____ ill.", options: ["is", "was", "were", "been"], answer: "was" },
  { id: 37, question: "Choose the correct spelling:", options: ["definately", "definitely", "definitly", "defenitely"], answer: "definitely" },
  { id: 38, question: "We’ll go for a walk if it ____ rain.", options: ["doesn’t", "don’t", "isn’t", "won’t"], answer: "doesn’t" },
  { id: 39, question: "He has been working here ____ five years.", options: ["since", "for", "from", "during"], answer: "for" },
  { id: 40, question: "I can’t find my keys. I think I ____ them.", options: ["lost", "have lost", "lose", "am losing"], answer: "have lost" },
  { id: 41, question: "She speaks English ____.", options: ["fluent", "fluently", "fluency", "flue"], answer: "fluently" },
  { id: 42, question: "He is not tall enough ____ play basketball.", options: ["for", "to", "so", "that"], answer: "to" },
  { id: 43, question: "My father works ____ a doctor.", options: ["as", "like", "for", "by"], answer: "as" },
  { id: 44, question: "Let’s meet ____ the evening.", options: ["in", "on", "at", "by"], answer: "in" },
  { id: 45, question: "She has a lot of ____.", options: ["homeworks", "homework", "homeworkes", "works"], answer: "homework" },
  { id: 46, question: "This is the ____ building in the city.", options: ["tall", "taller", "most tall", "tallest"], answer: "tallest" },
  { id: 47, question: "I usually go to bed ____ 11 p.m.", options: ["in", "on", "at", "by"], answer: "at" },
  { id: 48, question: "The synonym of 'begin' is ____.", options: ["end", "start", "close", "finish"], answer: "start" },
  { id: 49, question: "She hasn’t finished her work ____. ", options: ["yet", "already", "still", "ever"], answer: "yet" },
  { id: 50, question: "How long ____ you lived here?", options: ["are", "did", "have", "has"], answer: "have" },
];

module.exports = tests;
